# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "mpt3sas" "usbhid" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/11bbc574-deaf-43d5-a7f0-991b056eba1d";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/90B3-E60E";
      fsType = "vfat";
    };

  fileSystems."/mnt/sdd1" =
    { device = "/dev/disk/by-uuid/c19dd6ca-53a3-4e74-b8b5-3c37df3a6945";
      fsType = "ext4";
    };

  fileSystems."/mnt/sdb3" =
    { device = "/dev/disk/by-uuid/68c7645f-e732-44ec-9b14-44da69f42ab5";
      fsType = "btrfs";
    };

  fileSystems."/mnt/sda1" =
    { device = "/dev/disk/by-uuid/839730ec-8166-4ea4-b335-e7b981ddda15";
      fsType = "ext4";
    };

  fileSystems."/mnt/sdc1" =
    { device = "/dev/disk/by-uuid/11bbc574-deaf-43d5-a7f0-991b056eba1d";
      fsType = "ext4";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s25.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp9s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth8ebb973.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth93d330e.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth98ab007.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
